theme: jekyll-theme-primer
title: SmartDocumentor
description: All information in this document is confidential and for the exclusive access of SmartDocumentor customers. Access to this document is not permitted to any other entity without prior from DevScope. Any entity with access to this document, is obliged to the confidentiality of the same. 
